name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0  # Updated to use latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to use latest version
        with:
          node-version: '20'  # Update to Node.js 20

      - name: Set up environment variables
        run: |
          echo "BASE_API_URL=https://reqres.in/api" >> $GITHUB_ENV
          echo "BASE_URL=https://www.saucedemo.com/" >> $GITHUB_ENV
          echo "PERFORMANCE_URL=https://reqres.in" >> $GITHUB_ENV
          echo "USERNAME=standard_user" >> $GITHUB_ENV
          echo "PASS=secret_sauce" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm-run-all --parallel test:web test:mobile test:api

      - name: Generate Allure report
        run: npx allure generate ./allure-results -clean
